name: Validate Deployment
description: Shows deployed service and pod info.

inputs:
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Update kubeconfig for EKS cluster
      shell: bash
      run: |
        aws eks update-kubeconfig --region eu-north-1 --name ci-cd-cluster

    - name: Show service and pod info
      shell: bash
      run: |
        kubectl get svc
        kubectl get endpoints
        kubectl get pods
