name: Deploy to EKS
description: Updates kubeconfig and applies Kubernetes manifests.

inputs:
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Deploy to EKS
      shell: bash
      run: |
        aws eks update-kubeconfig --name ci-cd-cluster --region eu-north-1
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
