apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - name: devops
          image: 971632253057.dkr.ecr.us-east-1.amazonaws.com/app:latest
          ports:
            - containerPort: 3000