name: CI/CD pipeline deploy

on:
  push: 
    branches: [main]
  pull_request:
    types: [opened, synchronized, reopened]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      